/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IEpAim: typeof import('~icons/ep/aim')['default']
    IEpApple: typeof import('~icons/ep/apple')['default']
    IEpBaseball: typeof import('~icons/ep/baseball')['default']
    ISytChecked: typeof import('~icons/syt/checked')['default']
    ISytCompass: typeof import('~icons/syt/compass')['default']
  }
}
